### PR TITLE
Upgradeable csc module

### PR DESCRIPTION
**Pull request by GalaxySciTech**
Upgradeable csc module

### CODE REVIEW

**Comment by wgr523** [comment]
@openzeppelin/contracts/proxy/transparent/ProxyAdmin.sol is a well-known contract? Sure it is safe to use?

**Comment by wgr523** [comment]
Can you show using this proxy, how to call checkpoint smart contract? (I don't read js code very well, I only read sol code. So I don't know how to call it)

**Comment by GalaxySciTech** [comment]
> @openzeppelin/contracts/proxy/transparent/ProxyAdmin.sol is a well-known contract? Sure it is safe to use?

yeah its safe , and its standard sol library repo

**Comment by GalaxySciTech** [comment]
> Can you show using this proxy, how to call checkpoint smart contract? (I don't read js code very well, I only read sol code. So I don't know how to call it)

sure check code over here pls https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.9.3/contracts/proxy/transparent

**Review by wgr523 — APPROVED** [review]

**Pull request merged**
